from .backup import frm_backup
from .company import frm_company
from .configuration import frm_configuration
from .inspection import frm_inspection
from .login import frm_login
from .main import frm_main
from .notification_settings import frm_notification_settings
from .notifications import frm_notifications
from .options import frm_options
from .password import frm_password
from .permissions import frm_permissions
from .role import frm_role
from .table_view import frm_table_view
from .update import frm_update
from .user import frm_user
from .vehicle import frm_vehicle
from .vehicle_document import frm_vehicle_document
from .vehicles import frm_vehicles
from .workorder import frm_workorder
