from .backup import Ui_frm_backup
from .company import Ui_frm_company
from .configuration import Ui_frm_configuration
from .inspection import Ui_frm_inspection
from .login import Ui_frm_login
from .main import Ui_frm_main
from .password import Ui_frm_password
from .permission import Ui_frm_permission
from .permissions import Ui_frm_permissions
from .role import Ui_frm_role
from .table_view import Ui_frm_table_view
from .type_vehicle_document import Ui_frm_type_vehicle_document
from .types_vehicle_documents import Ui_frm_types_vehicle_documents
from .user import Ui_frm_user
from .vehicle import Ui_frm_vehicle
from .vehicle_document import Ui_frm_vehicle_document
from .vehicles import Ui_frm_vehicles
from .workorder import Ui_frm_workorder