# Form implementation generated from reading ui file 'views/forms_ui/document_name.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_document_name(object):
    def setupUi(self, frm_document_name):
        frm_document_name.setObjectName("frm_document_name")
        frm_document_name.resize(497, 132)
        self.gridLayout = QtWidgets.QGridLayout(frm_document_name)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_close = QtWidgets.QPushButton(parent=frm_document_name)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_save = QtWidgets.QPushButton(parent=frm_document_name)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lbl_document_name = QtWidgets.QLabel(parent=frm_document_name)
        self.lbl_document_name.setObjectName("lbl_document_name")
        self.horizontalLayout_2.addWidget(self.lbl_document_name)
        self.txt_document_name = QtWidgets.QLineEdit(parent=frm_document_name)
        self.txt_document_name.setObjectName("txt_document_name")
        self.horizontalLayout_2.addWidget(self.txt_document_name)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 0, 0, 1, 1)

        self.retranslateUi(frm_document_name)
        QtCore.QMetaObject.connectSlotsByName(frm_document_name)
        frm_document_name.setTabOrder(self.txt_document_name, self.btn_close)
        frm_document_name.setTabOrder(self.btn_close, self.btn_save)

    def retranslateUi(self, frm_document_name):
        _translate = QtCore.QCoreApplication.translate
        frm_document_name.setWindowTitle(_translate("frm_document_name", "Nombre de documento"))
        self.btn_close.setText(_translate("frm_document_name", "Cerrar"))
        self.btn_save.setText(_translate("frm_document_name", "Guardar"))
        self.lbl_document_name.setText(_translate("frm_document_name", "Nombre"))
