# Form implementation generated from reading ui file 'views/forms_ui/notifications.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_notifications(object):
    def setupUi(self, frm_notifications):
        frm_notifications.setObjectName("frm_notifications")
        frm_notifications.resize(553, 391)
        self.gridLayout = QtWidgets.QGridLayout(frm_notifications)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_close = QtWidgets.QPushButton(parent=frm_notifications)
        self.btn_close.setObjectName("btn_close")
        self.gridLayout.addWidget(self.btn_close, 1, 0, 1, 1)
        self.tvw_notifications = QtWidgets.QTreeView(parent=frm_notifications)
        self.tvw_notifications.setObjectName("tvw_notifications")
        self.gridLayout.addWidget(self.tvw_notifications, 0, 0, 1, 1)

        self.retranslateUi(frm_notifications)
        QtCore.QMetaObject.connectSlotsByName(frm_notifications)

    def retranslateUi(self, frm_notifications):
        _translate = QtCore.QCoreApplication.translate
        frm_notifications.setWindowTitle(_translate("frm_notifications", "Notificaciones"))
        self.btn_close.setText(_translate("frm_notifications", "Cerrar"))
