# Form implementation generated from reading ui file 'views/forms_ui/password.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_password(object):
    def setupUi(self, frm_password):
        frm_password.setObjectName("frm_password")
        frm_password.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        frm_password.resize(487, 145)
        self.gridLayout_3 = QtWidgets.QGridLayout(frm_password)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_password = QtWidgets.QLabel(parent=frm_password)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout_2.addWidget(self.lbl_password, 0, 0, 1, 1)
        self.lbl_repeat_password = QtWidgets.QLabel(parent=frm_password)
        self.lbl_repeat_password.setObjectName("lbl_repeat_password")
        self.gridLayout_2.addWidget(self.lbl_repeat_password, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.txt_password = QtWidgets.QLineEdit(parent=frm_password)
        self.txt_password.setObjectName("txt_password")
        self.gridLayout.addWidget(self.txt_password, 0, 0, 1, 1)
        self.txt_repeat_password = QtWidgets.QLineEdit(parent=frm_password)
        self.txt_repeat_password.setObjectName("txt_repeat_password")
        self.gridLayout.addWidget(self.txt_repeat_password, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_cancel = QtWidgets.QPushButton(parent=frm_password)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_4.addWidget(self.btn_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(parent=frm_password)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)

        self.retranslateUi(frm_password)
        QtCore.QMetaObject.connectSlotsByName(frm_password)

    def retranslateUi(self, frm_password):
        _translate = QtCore.QCoreApplication.translate
        frm_password.setWindowTitle(_translate("frm_password", "Gestor Contraseña"))
        self.lbl_password.setText(_translate("frm_password", "Contraseña"))
        self.lbl_repeat_password.setText(_translate("frm_password", "Repetir contraseña"))
        self.btn_cancel.setText(_translate("frm_password", "Cancelar"))
        self.btn_save.setText(_translate("frm_password", "Guardar"))
