# Form implementation generated from reading ui file 'nexus_admin_client/views/forms_ui/permission.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_permission(object):
    def setupUi(self, frm_permission):
        frm_permission.setObjectName("frm_permission")
        frm_permission.resize(400, 131)
        self.gridLayout = QtWidgets.QGridLayout(frm_permission)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(parent=frm_permission)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lbl_description = QtWidgets.QLabel(parent=frm_permission)
        self.lbl_description.setObjectName("lbl_description")
        self.verticalLayout.addWidget(self.lbl_description)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txt_name = QtWidgets.QLineEdit(parent=frm_permission)
        self.txt_name.setObjectName("txt_name")
        self.gridLayout_2.addWidget(self.txt_name, 0, 0, 1, 1)
        self.txt_description = QtWidgets.QLineEdit(parent=frm_permission)
        self.txt_description.setObjectName("txt_description")
        self.gridLayout_2.addWidget(self.txt_description, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_close = QtWidgets.QPushButton(parent=frm_permission)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_4.addWidget(self.btn_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_save = QtWidgets.QPushButton(parent=frm_permission)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(frm_permission)
        QtCore.QMetaObject.connectSlotsByName(frm_permission)

    def retranslateUi(self, frm_permission):
        _translate = QtCore.QCoreApplication.translate
        frm_permission.setWindowTitle(_translate("frm_permission", "Permiso"))
        self.lbl_name.setText(_translate("frm_permission", "Nombre"))
        self.lbl_description.setText(_translate("frm_permission", "Descripción"))
        self.btn_close.setText(_translate("frm_permission", "Cerrar"))
        self.btn_save.setText(_translate("frm_permission", "Guardar"))
