# Form implementation generated from reading ui file 'views/forms_ui/permissions.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_permissions(object):
    def setupUi(self, frm_permissions):
        frm_permissions.setObjectName("frm_permissions")
        frm_permissions.resize(222, 248)
        self.gridLayout = QtWidgets.QGridLayout(frm_permissions)
        self.gridLayout.setObjectName("gridLayout")
        self.tvw_permissions = QtWidgets.QTableView(parent=frm_permissions)
        self.tvw_permissions.setObjectName("tvw_permissions")
        self.gridLayout.addWidget(self.tvw_permissions, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_close = QtWidgets.QPushButton(parent=frm_permissions)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_print = QtWidgets.QPushButton(parent=frm_permissions)
        self.btn_print.setObjectName("btn_print")
        self.horizontalLayout.addWidget(self.btn_print)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(frm_permissions)
        QtCore.QMetaObject.connectSlotsByName(frm_permissions)

    def retranslateUi(self, frm_permissions):
        _translate = QtCore.QCoreApplication.translate
        frm_permissions.setWindowTitle(_translate("frm_permissions", "Dialog"))
        self.btn_close.setText(_translate("frm_permissions", "Cerrar"))
        self.btn_print.setText(_translate("frm_permissions", "Imprimir"))
