# Form implementation generated from reading ui file 'nexus_admin_client/views/forms_ui/table_view.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frm_table_view(object):
    def setupUi(self, frm_table_view):
        frm_table_view.setObjectName("frm_table_view")
        frm_table_view.resize(452, 424)
        self.gridLayout = QtWidgets.QGridLayout(frm_table_view)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_view = QtWidgets.QTableView(parent=frm_table_view)
        self.table_view.setObjectName("table_view")
        self.verticalLayout.addWidget(self.table_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_close = QtWidgets.QPushButton(parent=frm_table_view)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout.addWidget(self.btn_close)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_edit = QtWidgets.QPushButton(parent=frm_table_view)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_add = QtWidgets.QPushButton(parent=frm_table_view)
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_delete = QtWidgets.QPushButton(parent=frm_table_view)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 2)

        self.retranslateUi(frm_table_view)
        QtCore.QMetaObject.connectSlotsByName(frm_table_view)

    def retranslateUi(self, frm_table_view):
        _translate = QtCore.QCoreApplication.translate
        frm_table_view.setWindowTitle(_translate("frm_table_view", "Dialog"))
        self.btn_close.setText(_translate("frm_table_view", "Cerrar"))
        self.btn_edit.setText(_translate("frm_table_view", "Editar"))
        self.btn_add.setText(_translate("frm_table_view", "Añadir"))
        self.btn_delete.setText(_translate("frm_table_view", "Eliminar"))
